---
title: "Lab4"
author: "Akhila Nekkanti"
date: "5/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```



# Writing a summary function:
Write a function that takes a given data frame as its first argument, a column to summarize as its second argument, and any set of other columns to summary operations by as the third argument.


```{r final-function, eval=FALSE, include=TRUE}

descriptives <- function(df, outcome, ..., .fun = list(n = function(x) length(x),
                                             n_valid = function(x) sum(!is.na(x)),
                                             n_missing = function(x) sum(is.na(x)),
                                             mean = function(x) mean(x, na.rm = TRUE),
                                             sd = function(x) sd(x, na.rm = TRUE),
                                             min = function(x) min(x, na.rm = TRUE),
                                             max = function(x) max(x, na.rm = TRUE))) {
  library(dplyr)
  df_name <- deparse(substitute(df))
  outcome_name <- deparse(substitute(outcome))
            if(!is.data.frame(df)) { 
              
               stop(df_name, " is not a data frame")
            } 
  
            if(!is.numeric(pull(df, {{outcome}}))) {
              
               stop(outcome_name, " is not numeric")
            }
  
            if(is.numeric(pull(df, ...))) {
              
              warning(" Grouping variables are not categorical")
            }
 
  df %>% 
    group_by(...) %>% 
    summarise_at(vars({{outcome}}), .funs = .fun)
}


library(tidyverse)
#test for df 
descriptives(mean, tvhours, marital)

#test for outcome numeric
descriptives(gss_cat, marital, tvhours)

#test for grouping variable categorical 
descriptives(gss_cat, tvhours, age)


```




```{r old-attempts, eval=FALSE, include=FALSE}

listof_fun <- list(
  n = function(x) length(x),
  n_valid = function(x) sum(!is.na(x)),
  mean = function(x) mean(x),
  sd = function(x) sd(x),
  min = function(x) min(x),
  max = function(x) max(x)
)


smry_function <- function(df, outcome, ..., .fun = list(n = function(x) length(x),
                                             n_valid = function(x) sum(!is.na(x)),
                                             mean = function(x) mean(x),
                                             sd = function(x) sd(x),
                                             min = function(x) min(x),
                                             max = function(x) max(x))) {
  df %>% 
    group_by(...) %>% 
    summarise_at(vars({{outcome}}), .funs = .fun)
}

smry_function(gss_cat, tvhours, marital, race, rincome, relig, .fun = list(mean, median))
gss_cat

#list
f <- list(funs(
  n, "total count", length(.),
  n_valid, "nv", length(., na.rm = TRUE),
  mean, "mean", mean(., na.rm = TRUE)))


func <- function(data, 
                 var,
                 ...,
                 .descriptive = list(funs(
  n, "total count", length(.),
  n_valid, "nv", length(., na.rm = TRUE),
  mean, "mean", mean(., na.rm = TRUE)))) {
  
  dplyr::group_by(...) %>% 
    summarise_at(vars({{var}}), .funs = .descriptive)
}

func(airquality, Solar.R, Day, .descriptive = list(mean))
View(airquality)

  # create a list of functions 
f1 <- function(d,x) {
  d %>% 
  mutate(
   n = length(x),
   z = na.omit(x),
   n_valid = length(z),
   mean = mean(z),
   sd = sd(z),
   min = min(z),
   max = max(z))
   return(as.tibble(c(n = n, 
                      n_valid =n_valid, 
                      mean=mean,
                      sd=sd,
                      min=min,
                      max=max)))
}


f1(airquality, "Solar.R")

#total observations
n <- airquality %>% 
  select(Solar.R) %>% 
  count()

#total non-missing
n_valid <- airquality %>% 
  select(Solar.R) %>% 
  na.omit() %>% 
  count()
n_valid

#total missing
n_missing <- airquality %>% 
  select(Solar.R) %>% 
  summarise(sum(is.na(.)))



```


